package com.example.cocktaildb.screen.createrecipe
import android.content.Context
import android.net.Uri
import android.util.Log
import com.example.cocktaildb.R
import com.example.cocktaildb.data.model.Recipe
import com.example.cocktaildb.data.model.RecipeImage
import com.example.cocktaildb.data.model.RecipeIngredient
import com.example.cocktaildb.data.repository.AuthRepository
import com.example.cocktaildb.data.repository.FirebaseRepository
import com.example.cocktaildb.utils.ImageLoader
import com.example.cocktaildb.utils.base.BasePresenter
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.cancel

class CreateRecipePresenter(
    private val context: Context,
    private val firebaseRepository: FirebaseRepository,
    private val authRepository: AuthRepository
) : CreateRecipeContract.Presenter {

    private var view: CreateRecipeContract.View? = null
    private val presenterScope = CoroutineScope(Dispatchers.Main + Job())

    override fun setView(view: CreateRecipeContract.View?) {
        this.view = view
    }

    override fun onStart() {
        // Initialize any resources when presenter starts
    }

    override fun onStop() {
        presenterScope.cancel() // Cancel all coroutines when stopping
        view = null
    }

    override fun saveRecipe(
        name: String,
        instructions: String,
        imageUrl: String,
        ingredients: List<String>,
        measures: List<String>,
        category: String,
        glass: String,
        alcoholic: Boolean
    ) {
        // Validation
        if (name.isBlank()) {
            view?.showError(context.getString(R.string.error_recipe_name_empty))
            return
        }

        if (instructions.isBlank()) {
            view?.showError(context.getString(R.string.error_instructions_empty))
            return
        }

        if (ingredients.isEmpty() || ingredients.any { it.isBlank() }) {
            view?.showError(context.getString(R.string.error_add_at_least_one_ingredient))
            return
        }

        view?.showLoading(true)

        // Save recipe using coroutines
        presenterScope.launch(Dispatchers.IO) {
            try {
                // Get current user
                val currentUser = authRepository.getCurrentUser()
                val uid = currentUser?.uid ?: run {
                    withContext(Dispatchers.Main) {
                        view?.showLoading(false)
                        view?.showError(context.getString(R.string.error_user_not_authenticated))
                    }
                    return@launch
                }

                // Create Recipe object
                val recipe = Recipe(
                    id = "", // Will be generated by Firebase service
                    uid = uid,
                    name = name,
                    description = "", // Can be added later if needed
                    instructions = instructions,
                    prepTimeMinutes = 0, // Can be added to UI later
                    difficultyLevel = "Medium", // Default, can be added to UI
                    category = category,
                    alcoholic = if (alcoholic) "Alcoholic" else "Non alcoholic",
                    servings = 1, // Default, can be added to UI
                    createdAt = System.currentTimeMillis(),
                    updatedAt = System.currentTimeMillis(),
                    isPublic = true, // Default to public
                    viewCount = 0
                )

                // Save recipe to Firebase
                val result = firebaseRepository.createRecipe(recipe)

                if (result.isSuccess) {
                    val recipeId = result.getOrThrow()
                    Log.d("CreateRecipePresenter", "Recipe saved with ID: $recipeId")

                    // Save ingredients as separate entities
                    saveRecipeIngredients(recipeId, ingredients, measures)

                    // Save recipe image if provided
                    if (imageUrl.isNotBlank()) {
                        saveRecipeImage(recipeId, imageUrl)
                    }

                    withContext(Dispatchers.Main) {
                        view?.showLoading(false)
                        view?.showSuccess("Recipe saved successfully!")
                        view?.navigateToMyRecipes()
                    }
                } else {
                    val error = result.exceptionOrNull()
                    withContext(Dispatchers.Main) {
                        view?.showLoading(false)
                        view?.showError(context.getString(R.string.error_failed_to_save_recipe, error?.message ?: "Unknown error"))
                    }
                }

            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    view?.showLoading(false)
                    view?.showError(context.getString(R.string.error_failed_to_save_recipe, e.message ?: "Unknown error"))
                }
            }
        }
    }

    private suspend fun saveRecipeIngredients(recipeId: String, ingredients: List<String>, measures: List<String>) {
        val failedIngredients = mutableListOf<String>()
        try {
            for (i in ingredients.indices) {
                val ingredientName = ingredients[i].trim()
                if (ingredientName.isNotBlank()) {
                    val measure = if (i < measures.size) measures[i].trim() else ""
                    val recipeIngredient = RecipeIngredient(
                        id = "",
                        recipeId = recipeId,
                        ingredientName = ingredientName,
                        quantity = measure,
                        unit = "",
                        isOptional = false,
                        notes = ""
                    )
                    val result = firebaseRepository.addRecipeIngredient(recipeIngredient)
                    if (result.isFailure) {
                        Log.e("CreateRecipePresenter", "Failed to save ingredient: $ingredientName")
                        failedIngredients.add(ingredientName)
                    }
                }
            }
            if (failedIngredients.isNotEmpty()) {
                withContext(Dispatchers.Main) {
                    view?.showError(context.getString(R.string.warning_ingredients_not_saved, failedIngredients.joinToString(", ")))
                }
            }
        } catch (e: Exception) {
            Log.e("CreateRecipePresenter", "Error saving ingredients: ${e.message}")
            withContext(Dispatchers.Main) {
                view?.showError(context.getString(R.string.error_saving_ingredients, e.message ?: "Unknown error"))
            }
        }
    }

    private suspend fun saveRecipeImage(recipeId: String, imageUrl: String) {
        try {
            Log.d("CreateRecipePresenter", "Starting to save image with URL: $imageUrl")

            val uploadResult = if (imageUrl.startsWith("content://")) {
                Log.d("CreateRecipePresenter", "Uploading content:// URI to ImgBB")
                val sourceUri = Uri.parse(imageUrl)
                firebaseRepository.uploadRecipeImage(context, sourceUri, recipeId)
            } else if (firebaseRepository.isImgBBUrl(imageUrl)) {
                Log.d("CreateRecipePresenter", "Using existing ImgBB URL: $imageUrl")
                Result.success(imageUrl)
            } else {
                Log.w("CreateRecipePresenter", "Unknown image URL format: $imageUrl, attempting upload")
                val sourceUri = Uri.parse(imageUrl)
                firebaseRepository.uploadRecipeImage(context, sourceUri, recipeId)
            }

            if (uploadResult.isSuccess) {
                val downloadUrl = uploadResult.getOrThrow()
                Log.d("CreateRecipePresenter", "Image uploaded successfully to ImgBB: $downloadUrl")

                val recipeImage = RecipeImage(
                    id = "",
                    recipeId = recipeId,
                    imageUrl = downloadUrl,
                    isPrimary = true,
                    caption = "",
                    uploadedAt = System.currentTimeMillis()
                )

                Log.d("CreateRecipePresenter", "Saving image record to Firestore")
                val result = firebaseRepository.addRecipeImage(recipeImage)
                if (result.isSuccess) {
                    Log.d("CreateRecipePresenter", "Recipe image saved successfully")
                } else {
                    val error = result.exceptionOrNull()
                    Log.e("CreateRecipePresenter", "Failed to save image record: ${error?.message}")
                    withContext(Dispatchers.Main) {
                        view?.showError(context.getString(R.string.warning_image_uploaded_save_failed))
                    }
                }
            } else {
                val error = uploadResult.exceptionOrNull()
                Log.e("CreateRecipePresenter", "Failed to upload image: ${error?.message}")
                withContext(Dispatchers.Main) {
                    view?.showError(context.getString(R.string.warning_recipe_saved_image_upload_failed, error?.message ?: "Unknown error"))
                }
            }
        } catch (e: Exception) {
            Log.e("CreateRecipePresenter", "Error saving recipe image: ${e.message}", e)
            withContext(Dispatchers.Main) {
                view?.showError(context.getString(R.string.warning_recipe_saved_image_save_failed, e.message ?: "Unknown error"))
            }
        }
    }

    override fun addIngredient() {
        view?.addIngredientField()
    }

    override fun removeIngredient(position: Int) {
        view?.removeIngredientField(position)
    }
}
