package com.example.cocktaildb.screen.createrecipe

import android.util.Log
import com.example.cocktaildb.data.model.Recipe
import com.example.cocktaildb.data.model.RecipeIngredient
import com.example.cocktaildb.data.repository.AuthRepository
import com.example.cocktaildb.data.repository.FirebaseRepository
import com.example.cocktaildb.utils.base.BasePresenter
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class CreateRecipePresenter(
    private val firebaseRepository: FirebaseRepository,
    private val authRepository: AuthRepository,
    private val coroutineScope: CoroutineScope
) : CreateRecipeContract.Presenter {

    private var view: CreateRecipeContract.View? = null

    override fun setView(view: CreateRecipeContract.View?) {
        this.view = view
    }

    override fun onStart() {
        // Initialize any resources when presenter starts
    }

    override fun onStop() {
        // Clean up resources when presenter stops
    }

    override fun saveRecipe(
        name: String,
        instructions: String,
        imageUrl: String,
        ingredients: List<String>,
        measures: List<String>,
        category: String,
        glass: String,
        alcoholic: Boolean
    ) {
        // Validation
        if (name.isBlank()) {
            view?.showError("Recipe name cannot be empty")
            return
        }

        if (instructions.isBlank()) {
            view?.showError("Instructions cannot be empty")
            return
        }

        if (ingredients.isEmpty() || ingredients.any { it.isBlank() }) {
            view?.showError("Please add at least one ingredient")
            return
        }

        view?.showLoading(true)

        // Save recipe using coroutines
        coroutineScope.launch(Dispatchers.IO) {
            try {
                // Get current user
                val currentUser = authRepository.getCurrentUser()
                val uid = currentUser?.uid ?: run {
                    withContext(Dispatchers.Main) {
                        view?.showLoading(false)
                        view?.showError("User not authenticated")
                    }
                    return@launch
                }

                // Create Recipe object
                val recipe = Recipe(
                    id = "", // Will be generated by Firebase service
                    uid = uid,
                    name = name,
                    description = "", // Can be added later if needed
                    instructions = instructions,
                    prepTimeMinutes = 0, // Can be added to UI later
                    difficultyLevel = "Medium", // Default, can be added to UI
                    category = category,
                    alcoholic = if (alcoholic) "Alcoholic" else "Non alcoholic",
                    servings = 1, // Default, can be added to UI
                    createdAt = System.currentTimeMillis(),
                    updatedAt = System.currentTimeMillis(),
                    isPublic = true, // Default to public
                    viewCount = 0
                )

                // Save recipe to Firebase
                val result = firebaseRepository.createRecipe(recipe)
                
                if (result.isSuccess) {
                    val recipeId = result.getOrThrow()
                    Log.d("CreateRecipePresenter", "Recipe saved with ID: $recipeId")

                    // Save ingredients as separate entities
                    saveRecipeIngredients(recipeId, ingredients, measures)

                    // Save recipe image if provided
                    if (imageUrl.isNotBlank()) {
                        // TODO: Implement saving recipe image
                        // saveRecipeImage(recipeId, imageUrl)
                    }

                    withContext(Dispatchers.Main) {
                        view?.showLoading(false)
                        view?.showSuccess("Recipe saved successfully!")
                        view?.navigateToMyRecipes()
                    }
                } else {
                    val error = result.exceptionOrNull()
                    withContext(Dispatchers.Main) {
                        view?.showLoading(false)
                        view?.showError("Failed to save recipe: ${error?.message}")
                    }
                }

            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    view?.showLoading(false)
                    view?.showError("Failed to save recipe: ${e.message}")
                }
            }
        }
    }

    private suspend fun saveRecipeIngredients(recipeId: String, ingredients: List<String>, measures: List<String>) {
        val failedIngredients = mutableListOf<String>()
        try {
            for (i in ingredients.indices) {
                val ingredientName = ingredients[i].trim()
                if (ingredientName.isNotBlank()) {
                    val measure = if (i < measures.size) measures[i].trim() else ""
                    val recipeIngredient = RecipeIngredient(
                        id = "",
                        recipeId = recipeId,
                        ingredientName = ingredientName,
                        quantity = measure,
                        unit = "",
                        isOptional = false,
                        notes = ""
                    )
                    val result = firebaseRepository.addRecipeIngredient(recipeIngredient)
                    if (result.isFailure) {
                        Log.e("CreateRecipePresenter", "Failed to save ingredient: $ingredientName")
                        failedIngredients.add(ingredientName)
                    }
                }
            }
            if (failedIngredients.isNotEmpty()) {
                withContext(Dispatchers.Main) {
                    view?.showError("Warning: The following ingredients could not be saved: ${failedIngredients.joinToString(", ")}")
                }
            }
        } catch (e: Exception) {
            Log.e("CreateRecipePresenter", "Error saving ingredients: ${e.message}")
            withContext(Dispatchers.Main) {
                view?.showError("Error saving ingredients: ${e.message}")
            }
        }
    }

    override fun addIngredient() {
        view?.addIngredientField()
    }

    override fun removeIngredient(position: Int) {
        view?.removeIngredientField(position)
    }
}
